package com.wisdom.nhoa.util.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wisdom.nhoa.homepage.model.CalendarEventModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CALENDAR_EVENT_MODEL".
*/
public class CalendarEventModelDao extends AbstractDao<CalendarEventModel, Long> {

    public static final String TABLENAME = "CALENDAR_EVENT_MODEL";

    /**
     * Properties of entity CalendarEventModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Sqid = new Property(0, Long.class, "sqid", true, "_id");
        public final static Property Id = new Property(1, String.class, "id", false, "SCHEDULEID");
        public final static Property Datetxt = new Property(2, String.class, "datetxt", false, "DATETXT");
        public final static Property Starttime = new Property(3, String.class, "starttime", false, "STARTTIME");
        public final static Property Endtime = new Property(4, String.class, "endtime", false, "ENDTIME");
        public final static Property Calendarid = new Property(5, int.class, "calendarid", false, "CALENDARID");
        public final static Property Title = new Property(6, String.class, "title", false, "TITLE");
        public final static Property Isallday = new Property(7, boolean.class, "isallday", false, "ISALLDAY");
        public final static Property Location = new Property(8, String.class, "location", false, "LOCATION");
    }


    public CalendarEventModelDao(DaoConfig config) {
        super(config);
    }
    
    public CalendarEventModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CALENDAR_EVENT_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: sqid
                "\"SCHEDULEID\" TEXT," + // 1: id
                "\"DATETXT\" TEXT," + // 2: datetxt
                "\"STARTTIME\" TEXT," + // 3: starttime
                "\"ENDTIME\" TEXT," + // 4: endtime
                "\"CALENDARID\" INTEGER NOT NULL ," + // 5: calendarid
                "\"TITLE\" TEXT," + // 6: title
                "\"ISALLDAY\" INTEGER NOT NULL ," + // 7: isallday
                "\"LOCATION\" TEXT);"); // 8: location
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CALENDAR_EVENT_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CalendarEventModel entity) {
        stmt.clearBindings();
 
        Long sqid = entity.getSqid();
        if (sqid != null) {
            stmt.bindLong(1, sqid);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String datetxt = entity.getDatetxt();
        if (datetxt != null) {
            stmt.bindString(3, datetxt);
        }
 
        String starttime = entity.getStarttime();
        if (starttime != null) {
            stmt.bindString(4, starttime);
        }
 
        String endtime = entity.getEndtime();
        if (endtime != null) {
            stmt.bindString(5, endtime);
        }
        stmt.bindLong(6, entity.getCalendarid());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
        stmt.bindLong(8, entity.getIsallday() ? 1L: 0L);
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(9, location);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CalendarEventModel entity) {
        stmt.clearBindings();
 
        Long sqid = entity.getSqid();
        if (sqid != null) {
            stmt.bindLong(1, sqid);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String datetxt = entity.getDatetxt();
        if (datetxt != null) {
            stmt.bindString(3, datetxt);
        }
 
        String starttime = entity.getStarttime();
        if (starttime != null) {
            stmt.bindString(4, starttime);
        }
 
        String endtime = entity.getEndtime();
        if (endtime != null) {
            stmt.bindString(5, endtime);
        }
        stmt.bindLong(6, entity.getCalendarid());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
        stmt.bindLong(8, entity.getIsallday() ? 1L: 0L);
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(9, location);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CalendarEventModel readEntity(Cursor cursor, int offset) {
        CalendarEventModel entity = new CalendarEventModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // sqid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // datetxt
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // starttime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // endtime
            cursor.getInt(offset + 5), // calendarid
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // title
            cursor.getShort(offset + 7) != 0, // isallday
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // location
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CalendarEventModel entity, int offset) {
        entity.setSqid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDatetxt(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStarttime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEndtime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCalendarid(cursor.getInt(offset + 5));
        entity.setTitle(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsallday(cursor.getShort(offset + 7) != 0);
        entity.setLocation(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CalendarEventModel entity, long rowId) {
        entity.setSqid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CalendarEventModel entity) {
        if(entity != null) {
            return entity.getSqid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CalendarEventModel entity) {
        return entity.getSqid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
