package com.wisdom.nhoa.util.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wisdom.nhoa.homepage.model.CalendarEventModel;
import com.wisdom.nhoa.homepage.model.LeaderScheduleModel;
import com.wisdom.nhoa.homepage.model.MsgListModel;

import com.wisdom.nhoa.util.greendao.CalendarEventModelDao;
import com.wisdom.nhoa.util.greendao.LeaderScheduleModelDao;
import com.wisdom.nhoa.util.greendao.MsgListModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig calendarEventModelDaoConfig;
    private final DaoConfig leaderScheduleModelDaoConfig;
    private final DaoConfig msgListModelDaoConfig;

    private final CalendarEventModelDao calendarEventModelDao;
    private final LeaderScheduleModelDao leaderScheduleModelDao;
    private final MsgListModelDao msgListModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        calendarEventModelDaoConfig = daoConfigMap.get(CalendarEventModelDao.class).clone();
        calendarEventModelDaoConfig.initIdentityScope(type);

        leaderScheduleModelDaoConfig = daoConfigMap.get(LeaderScheduleModelDao.class).clone();
        leaderScheduleModelDaoConfig.initIdentityScope(type);

        msgListModelDaoConfig = daoConfigMap.get(MsgListModelDao.class).clone();
        msgListModelDaoConfig.initIdentityScope(type);

        calendarEventModelDao = new CalendarEventModelDao(calendarEventModelDaoConfig, this);
        leaderScheduleModelDao = new LeaderScheduleModelDao(leaderScheduleModelDaoConfig, this);
        msgListModelDao = new MsgListModelDao(msgListModelDaoConfig, this);

        registerDao(CalendarEventModel.class, calendarEventModelDao);
        registerDao(LeaderScheduleModel.class, leaderScheduleModelDao);
        registerDao(MsgListModel.class, msgListModelDao);
    }
    
    public void clear() {
        calendarEventModelDaoConfig.clearIdentityScope();
        leaderScheduleModelDaoConfig.clearIdentityScope();
        msgListModelDaoConfig.clearIdentityScope();
    }

    public CalendarEventModelDao getCalendarEventModelDao() {
        return calendarEventModelDao;
    }

    public LeaderScheduleModelDao getLeaderScheduleModelDao() {
        return leaderScheduleModelDao;
    }

    public MsgListModelDao getMsgListModelDao() {
        return msgListModelDao;
    }

}
